import type { Metadata } from "next";
import "./globals.css";
import IntlProvider from "./components/locale/IntlProvider";

export const metadata: Metadata = {
    title: "INSAI",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html suppressHydrationWarning>
            <body>
                <IntlProvider>{children}</IntlProvider>
            </body>
        </html>
    );
}
